language: generic

install_default: &setup
  - git clone --depth 1 https://github.com/creationix/nvm.git ./nvm
  - source ./nvm/nvm.sh
  - export NODE_VERSION=4
  - nvm install ${NODE_VERSION}
  - nvm use ${NODE_VERSION}
  - bash --version

linux_default: &linux_setup
  # logbt by default sets up core pattern since it
  # is intended to be run as root in production,
  # but here we set up as root beforehand to be able to
  # run test as non-sudo
  - sudo bash -c "echo "/tmp/logbt-coredumps/core.%p" > /proc/sys/kernel/core_pattern"
  - export CORE_PATTERN=false

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'gdb','libstdc++-5-dev']
      before_install: *linux_setup
      install: *setup
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'gdb','libstdc++-5-dev']
      before_install: *linux_setup
      install: *setup
    - os: osx
      osx_image: xcode7
      install: *setup

script:
  - sudo ./test/unit.sh
