language: generic

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'gdb','libstdc++-5-dev']
      script:
        - bash --version
        # sudo is only required currently on linux
        - sudo ./test/unit.sh
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'gdb','libstdc++-5-dev']
      script:
        - bash --version
        # sudo is only required currently on linux
        - sudo ./test/unit.sh
    - os: osx
      osx_image: xcode7
      script:
        - bash --version
        # sudo is only required currently on linux
        - ./test/unit.sh