language: generic

install_default: &setup
  - git clone --depth 1 https://github.com/creationix/nvm.git ./nvm
  - source ./nvm
  - export NODE_VERSION=4
  - nvm install ${NODE_VERSION}
  - nvm use ${NODE_VERSION}
  - bash --version

matrix:
  include:
    - os: linux
      sudo: required
      dist: precise
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'gdb','libstdc++-5-dev']
      install: *setup
      script:
        # sudo is only required currently on linux
        - sudo ./test/unit.sh
    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test']
          packages: [ 'gdb','libstdc++-5-dev']
      install: *setup
      script:
        # sudo is only required currently on linux
        - sudo ./test/unit.sh
    - os: osx
      osx_image: xcode7
      install: *setup
      script:
        - ./test/unit.sh